[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -vv"
testpaths = [
    "tests",
    "integration"
    ]

[tool.flake8]
exclude = [".venv", "build"] 


[tool.black]
line-length = 79
target-version = ["py39"]
