name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12.2, 3.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Project
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install '.[test]'
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --junitxml=test-result.xml
      - name: Publish JUnit results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-result.xml
          check_name: Test Result (Python ${{ matrix.python-version }})
